{% extends "main_layout.html" %}
{% block content %}
        <div class="d-flex align-items-center justify-content-center vh-100">
            <div class="text-center">
                <h1 class="display-1 fw-bold">{{ error_code }}</h1>
                <p class="fs-3"> <span class="text-danger">Opps!</span> Halaman Tidak Tersedia.</p>
                <p class="lead">
                    {{message}}
                </p>
                <a href="{{ url_for('formklasifikasi') }}" class="btn btn-primary">Back</a>
            </div>
        </div>
{% endblock %}