{% extends "main_layout.html" %}
{% block content %}
<style>
    .table{
        margin-bottom: 0px!important;
    }
</style>
<h4>
    Hasil Klasifikasi
</h4>


<div class="row">
    <div class="col-md-12">
        <div class="card">
            
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="card" style="padding: 10px;">
                            <div id="myChartPie1"  style="height:350px;"></div>
                        </div>
                    </div>
                    <!-- <div class="col-md-3">

                        <div class="card">
                                <img class="img-thumbnail rounded mx-auto d-block m-2" src="{{url_for('static', filename='Classification.png')}}" width="70%"alt="">
                        </div>
                    </div> -->

                    <div class="col-md-6">
                        <div class="table-responsive">

                            <table class="table table-bordered">
                                <tr>
                                    <td></td>
                                    <td class="font-weight-bold text-center" colspan="2">Total Kelas</td>
                                    
                                </tr>
                                <tr>
                                    <td><span class="badge badge-primary"> Total Kalimat Positif</span> </td>
                                    <td class="text-center">{{ dataHeader.total_positif}}</td>
                                </tr>
                                <tr>
                                    <td> <span class="badge badge-danger">Total Kalimat Negatif</span></td>
                                    <td class="text-center">{{ dataHeader.total_negatif}}</td>
                                </tr>
                                <tr>
                                    <td> <span class="badge badge-info">Total Kalimat Netral</span></td>
                                    <td class="text-center">{{ dataHeader.total_netral}}</td>
                                </tr>
                            </table> 

                            </div>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-12">
                        <div class="card" style="padding: 10px;">
                            <div class="card ">
                                {{ text_berita }}
                            </div>

                            <!--<div class="table-responsive">

                                <table class="table table-bordered" >
                                    <thead>
                                      <tr>
                                        <th class="text-center" scope="col" style="width:30px">No</th>
                                        <th class="text-center" scope="col">Kalimat</th>
                                        <th class="text-center" scope="col">Setelah Praproses</th>
                                        <th class="text-center" scope="col">Kelas</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                        {% for list in data %}
                                            <tr>
                                                <td>
                                                    {{list.no}}
                                                </td>
                                                <td>
                                                    {{list.kalimat}}
                                                </td>
                                                <td>
                                                    {{list.after_praproses}}
                                                </td>
                                                <td>
                                                    {{list.flagging}}
                                                </td>
                                            </tr>
                                        {% endfor %}
    
                                    </tbody>
                                      
                                </table>
                            </div>-->
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/echarts/5.4.1/echarts.min.js"></script>

<script>

    function myFunc(vars) {
        return vars
    }
    myVar = myFunc({{dataHeader|tojson}})

    var myChartPie = echarts.init(document.getElementById('myChartPie1'));

    optionPie = {
        title: {
          text: 'Data by Class',
          subtext: 'News Sentence',
          left: 'center'
        },
        tooltip: {
          trigger: 'item'
        },
        legend: {
          orient: 'vertical',
          left: 'left'
        },
        series: [
          {
            name: 'Access From',
            type: 'pie',
            radius: '60%',
            data: [
                { 
                    value   : myVar.total_positif, 
                    name    : 'Positif', 
                    label   : {
                                show: true,
                                formatter: 'Positif {c} %',
                              }
                },
                { 
                    value   :  myVar.total_negatif, 
                    name    : 'Negatif', 
                    label   : {
                                show: true,
                                formatter: 'Negatif {c} %',
                              }
                },
                { 
                    value   : myVar.total_netral, 
                    name    : 'Netral', 
                    label   : {
                                show: true,
                                formatter: 'Netral {c} %',
                              }
                },
              
            ],
            emphasis: {
              itemStyle: {
                shadowBlur: 10,
                shadowOffsetX: 0,
                shadowColor: 'rgba(0, 0, 0, 0.5)'
              }
            }
          }
        ]
      };

      myChartPie.setOption(optionPie);

</script>
<!-- <p>Ini About</p> -->
{% endblock %}